# Generated by Django 3.2.4 on 2021-06-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='stater',
            new_name='starter',
        ),
    ]
